### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Abkasem** [urbanadventurer/Android-PIN-Bruteforce#151] opened 2024-02-04 14:26 UTC
What issue 
![Screenshot_٢٠٢٤٠٢٠٤-١٥٢٦٢١](https://github.com/urbanadventurer/Android-PIN-Bruteforce/assets/125785636/32c51638-fc7b-4fa9-9ad4-a24b1996b2fe)

**Comment by urbanadventurer** [comment] 2024-02-11 11:54
duplicate of #118

**Closed as completed by urbanadventurer** 2024-02-11 11:54 UTC
