### ISSUE TITLE
does it work on cubot kingkong3?

### ISSUE THREAD

**Issue by cokiere** [urbanadventurer/Android-PIN-Bruteforce#139] opened 2023-04-10 18:56 UTC
hi
I have a cubot kingkong 3 rooted. I installed nethunter through termux and i get this issue: 
HID device (/dev/hidg0) not found
thanks

![Screenshot_20230410-182537](https://user-images.githubusercontent.com/130388748/230964727-bb91d905-d751-4880-ba44-af56a068a516.png)

**Comment by urbanadventurer** [comment] 2024-01-16 10:54
Duplicate of #132

**Closed as completed by urbanadventurer** 2024-01-16 10:54 UTC
